### PR TITLE
For multiple processes, prompt the user to select one based on the pid

### LINKED ISSUE #32: For Multiple Processes With The Same Name, Allow Users to Choose the Process / Show the Processes available.
Right now, we are disallowing monitoring if there are multiple processes of the same name. As per @chrisnas' comment: https://github.com/Maoni0/realmon/pull/19#discussion_r754095252  we should allow the user to choose amongst different processes with the same name or at least display a list of processes.

### PR DESCRIPTION
**Pull request by MokoSan**
For the case of multiple processes, rather than exiting the process, prompt the user to choose one based on the PID.  This is to fix #32. 

The behavior is now like the following:
Administrator_ Windows PowerShell 2021-12-02 22-36-20

### CODE REVIEW

**Comment by Maoni0** [comment]
seems like it would be helpful to the user to display the commandline args of those processes for them to decide which pid they want. what do you think?

**Comment by MokoSan** [comment]
Definitely think it's a great idea! Thanks! Command line args are only available to other processes if we are in sudo/admin mode. The way to discern the sudo / admin mode for Linux and MacOs / Windows are different additionally, the methodology to get to command line args amongst the different OSes is different; the last commit before this comment takes care of this. 

A different prompt is presented to the user if they are in sudo/admin mode than if they are not.

## For Windows:

### Non-Admin
image

### Admin
image

## For Linux:

### Non-Sudo
image

### Sudo
image

**Comment by Maoni0** [comment]
sorry @MokoSan, I didn't get to your PRs earlier. I'm also starting my vacation so my response will be slow. I've talked to @mangod9 to see if he could review some of the PRs here while I'm OOF. 

right, you do need admin privilege to see other processes's cmdline args. I forgot about that. on linux EventPipe does not require you to have admin privilege so users could be both but on windows, since we are using ETW, it means you'd already need to have admin privilege. in your 1st pic (non admin on windows) are you able to actually monitor?

**Comment by MokoSan** [comment]
Thanks for taking a look! 

>  in your 1st pic (non admin on windows) are you able to actually monitor?

Yes - I am able to monitor without admin privileges (always have been able to minus the call stack work). 

Enjoy your vacation!

**Comment by MokoSan** [comment]
#39 will make doing this much easier as we'll have Spectre.CLI support. Will include this with this PR once #39 is merged.

**Comment by MokoSan** [comment]
@Maoni0, this PR is also ready to be merged with the latest rebased changes + additions to the different ``IConsoleOut`` impls. Additionally, I removed the requirement of being a super user for Linux / MacOS to read the commandline args as it's a simple file read. 

## Plain Text Prompt
Prompt_PlainText


## Spectre Prompt

image

**Comment by Maoni0** [comment]
awesome! thanks @MokoSan

**Pull request merged**
